# Generated by Django 6.0.6 on 2026-07-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('tara', models.CharField(max_length=100)),
                ('oras', models.CharField(max_length=100)),
                ('latitudine', models.FloatField()),
                ('longitudine', models.FloatField()),
                ('lungime_km', models.FloatField()),
                ('numar_viraje', models.IntegerField()),
                ('an_prima_cursa', models.IntegerField()),
                ('istorie', models.TextField()),
                ('imagine_url', models.CharField(max_length=500)),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'circuit',
            },
        ),
        migrations.CreateModel(
            name='Comentariu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_vizitator', models.CharField(max_length=100)),
                ('mesaj', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuite.circuit')),
            ],
            options={
                'db_table': 'comentariu',
            },
        ),
        migrations.CreateModel(
            name='MarePremiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('runda', models.IntegerField()),
                ('data_cursei', models.DateField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circuite.circuit')),
            ],
            options={
                'db_table': 'mare_premiu',
            },
        ),
    ]
